name: vaub-pnp-da

dataset:
  src: mnist
  tgt: mnist_m
  img_size: 32
  root: "data"
  num_classes: 10

epoch: 50
logger: false
load: true
save: false
save_path: "saved_models"
logger_path: "logs"
seed: 8080
gpus: 2
num_domain: 2

training:
  backbone: minimal32
  lr: 1e-4
  batch_size: 64
  num_workers: 24
  lambda_vaub: 1
  latent_dim: 32
  pz: "MoG"
  n_components: 1
  weight_decay: 0.0
  num_visual: 8

